name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pyodbc
        pip install pandas
        pip install openpyxl
        pip install playwright
        playwright install
   
      

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        artifact: test-results
        name: Workflow Report
        path: '*.xml'
        reporter: jest-junit

    
