# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME}}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
      DB_SERVERNAME: ${{ secrets.DB_SERVERNAME}}
      DB_TABLE: ${{ secrets.DB_TABLE}}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pyodbc
        pip install pandas
        pip install openpyxl
        pip install pytest-sqlalchemy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute SQL Query
      run: python test_db_operations.py
    - name: Test with pytest
      run: |
        pytest

