name: python package

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:[ubuntu-latest, macos-latest, windows-latest]
        python-version:
         - "3.8"
         - "3.9"
         -"3.12-dev"
         -"pypy-3.8"

     name: Test
     runs-on: ${{ matrix.os}}

     steps:
      - name: Checkout code
        uses: actions/checkout@vs3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install pytest .
      - name: Run sampleproj
        run: pytest
